project_id = "fcriintgtieznxcanxnp"

[functions.admin-users]
verify_jwt = false

[functions.cloudinary-sign]
verify_jwt = false

[functions.cloudinary-migrate]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.mailchimp-subscribe]
verify_jwt = false
