
DELETE FROM public.team_members;

INSERT INTO public.team_members (name, title, bio, image_url, linkedin_url, order_index, is_featured) VALUES
('Dr. Ade Oyedijo', 'Founder & Director', 'Dr Oyedijo is a Scholar currently based at the University of Leicester School of Business where he lectures in Operations and Supply Chain Management. Ade founded SBA and oversees its current activities.', 'https://societyofblackacademics.com/wp-content/uploads/2023/06/Dr-Ade-Oyedijo-e1687520059154.jpeg', 'https://www.linkedin.com/in/ade-oyedijo-25986260/?originalSubdomain=uk', 0, false),
('Dr. Mercy Denedo', 'Project Manager', 'Dr. Denedo is an Assistant Professor in Accounting at Durham University. She manages all SBA''s projects and assists in the planning of SBA''s annual conferences.', 'https://societyofblackacademics.com/wp-content/uploads/2023/06/Dr-Mercy-Denedo.jpg', 'https://www.linkedin.com/in/mercy-denedo-68071135/?originalSubdomain=uk', 1, false),
('Dr. Bola Babajide', 'Partnerships & External Engagement Manager', 'Dr. Babajide is a Senior Lecturer in Accounting and Finance at De Montfort University. She is responsible for SBA''s partnerships and external engagement activities.', 'https://societyofblackacademics.com/wp-content/uploads/2023/06/Dr-Bola-Babajide.jpg', 'https://www.linkedin.com/in/bola-o-babajide-64124352/?originalSubdomain=uk', 2, false),
('Steven Iorfa', 'Operations & Events Manager', 'Steven looks after SBA''s events and coordinates its operational activities. He is a doctoral researcher at the University of Portsmouth, looking at sustainability transitions in food systems.', 'https://societyofblackacademics.com/wp-content/uploads/2023/09/Steven-Iorfa-e1693896382495.jpeg', 'https://www.linkedin.com/in/steven-kator-iorfa-138641116/', 3, false),
('Juliet Ocheja', 'Company Secretary', 'Juliet is a qualified lawyer with extensive experience across the public sector, oil and gas, finance, and energy. She assists SBA and offers guidance on compliance and regulatory matters.', 'https://societyofblackacademics.com/wp-content/uploads/2023/06/Juliet-Ocheja.jpeg', 'https://www.linkedin.com/in/juliet-ocheja-66952362/?originalSubdomain=uk', 4, false),
('Oyebola Toyese', 'Marketing Manager', 'Oyebola Toyese is a specialist and consultant in branding, marketing, communications, and business growth. She provides support on SBA''s marketing and branding approach.', 'https://societyofblackacademics.com/wp-content/uploads/2023/06/Formal-2.jpeg', 'https://www.linkedin.com/in/oyebolatoyese/?originalSubdomain=uk', 5, false),
('Dr. Opeoluwa Aiyenitaju', 'Education Manager', 'Dr. Ope is an enthusiastic academic. She lectures in Business Information Systems at Manchester Metropolitan University and takes an integral role in SBA''s student outreach initiative as Education & Engagement Manager.', 'https://societyofblackacademics.com/wp-content/uploads/2023/08/Dr-Opeoluwa-Aiyenitaju-.jpeg', 'https://www.linkedin.com/in/opeoluwaadewolu?originalSubdomain=uk', 6, false),

('Professor Sally Everett', 'Vice Dean (Education), King''s Business School', 'Professor Sally Everett is Vice Dean (Education), Deputy Dean (interim), and Professor of Business Education at King''s Business School. A National Teaching Fellow and Principal Fellow of the HEA, she champions inclusive learning, teaching and assessment.', 'https://aheconferencedotcom1.files.wordpress.com/2022/03/sally-everett-small.jpg', NULL, 10, true),
('Professor Kevin Ibeh', 'Pro Vice-Chancellor (International), Birkbeck, University of London', 'Kevin Ibeh, PhD, FCIM, FRSA, is Professor of Marketing and International Business and Pro Vice-Chancellor (International) at Birkbeck, University of London. He is a leading authority on emerging African Multinational Enterprises.', 'https://societyofblackacademics.com/wp-content/uploads/2023/09/Professor-Kevin-Ibeh.jpeg', NULL, 11, true),
('Professor (Associate) Gillian Stokes', 'Associate Professor of Inclusive Social Research, UCL', 'Gillian is an Associate Professor of Inclusive Social Research at the UCL Social Research Institute. She conducts health-focused systematic reviews and is a qualified herbal practitioner, medical ethnobotanist and published poet.', 'https://societyofblackacademics.com/wp-content/uploads/2023/09/9-2.jpeg', NULL, 12, true),
('Professor Temidayo Akenroye', 'Faculty Member, University of Missouri-St Louis', 'Professor Temidayo Akenroye is a Faculty Member at the University of Missouri-St Louis and a Senior Visiting Fellow at Lagos Business School. He has published widely on sustainable supply chains and global value chains.', 'https://societyofblackacademics.com/wp-content/uploads/2023/09/Professor-Temidayo-Akenroye-1-1.jpeg', NULL, 13, true),
('Professor Nelarine Cornelius', 'Professor of Organisation Studies', 'Nelarine Cornelius is a Professor of Organisation Studies. Her research is in the areas of social justice, business in society and the evolution of management practices in emerging, fragile economies.', 'https://societyofblackacademics.com/wp-content/uploads/2023/09/Nelarine-1.jpeg', NULL, 14, true),
('Professor Kenneth Amaeshi', 'Professor of Sustainable Finance and Governance, School of Transnational Governance', 'Kenneth Amaeshi is a Professor of Sustainable Finance and Governance at the School of Transnational Governance and Chair in Business and Sustainable Development at the University of Edinburgh. He is a leading scholar on sustainable business and finance in the global south.', 'https://societyofblackacademics.com/wp-content/uploads/2023/09/Kenneth-Amaeshi.jpg', NULL, 15, true),
('Professor Gloria Agyemang', 'Professor of Accounting, Royal Holloway, University of London', 'Gloria Agyemang is a Professor of Accounting at Royal Holloway, University of London. Her research interests include NGO accountability, performance management, and accounting in less developed and emerging economies.', 'https://societyofblackacademics.com/wp-content/uploads/2023/09/Gloria-1.jpeg', NULL, 16, true);
