// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fcriintgtieznxcanxnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjcmlpbnRndGllem54Y2FueG5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1OTQxNjgsImV4cCI6MjA3MjE3MDE2OH0.g2eoKQNcCK8kiPqTAmBcpdQ2Nf7XLRAQLWZsT0h34JM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});